version: '3'
services:
  web:
    container_name: mysql_prueba
    ports:
      - "3307:3306"
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=12345678"
      - "MYSQL_DATABASE=docker-db"
      - "MYSQL_USER=docker-user"
      - "MYSQL_PASSWORD=123456"